version: '3'
services:
  postgresdb:
    image: "postgres:16"
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${PG_DB}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
    ports:
      - '5434:5432'
    volumes:
      - 'postgres-data:/usr/local/pgsql/data'
  backend:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8000:8001"
    depends_on:
      - postgresdb
volumes:
  postgres-data:
